### ISSUE TITLE
Error while training the model

### ISSUE THREAD

**Issue by aditijadhav38** [NextGenVest/google-smart-reply-2017#3]
Hi,
I am getting the following error while training the model.

**Traceback (most recent call last):
  File "main_dual_encoder_dense.py", line 55, in <module>
    dual_encoder_trainer.train_main(hparams)
  File "/home/aditi/google-smart-reply-2017/models/dual_encoder_dense/dual_encoder_trainer.py", line 142, in train_main
    exp.save()
  File "/root/anaconda3/envs/tensorflow/lib/python3.5/site-packages/test_tube/log.py", line 244, in save
    json.dump(self.tags, file, ensure_ascii=False)
  File "/root/anaconda3/envs/tensorflow/lib/python3.5/json/__init__.py", line 178, in dump
    for chunk in iterable:
  File "/root/anaconda3/envs/tensorflow/lib/python3.5/json/encoder.py", line 429, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/root/anaconda3/envs/tensorflow/lib/python3.5/json/encoder.py", line 403, in _iterencode_dict
    yield from chunks
  File "/root/anaconda3/envs/tensorflow/lib/python3.5/json/encoder.py", line 436, in _iterencode
    o = _default(o)
  File "/root/anaconda3/envs/tensorflow/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <bound method HyperOptArgumentParser.optimize_parallel of HyperOptArgumentParser(prog='main_dual_encoder_dense.py', usage=None, description=None, formatter_class=<class 'argparse.HelpFormatter'>, conflict_handler='error', add_help=True)> is not JSON serializable**

Can you please tell me how to solve, because I am not able to solve this.

**Comment by mahyar-osn** [comment]
I have the same issue. Any suggestions?? Thanks.

**Comment by williamFalcon** [comment]
@aditijadhav38 I may have fixed that issue just now. Git pull and update the requirements.txt and lmk if that worked.

**Comment by aditijadhav38** [comment]
@williamFalcon Thanks for your feedback. I'll update the changes accordingly.

**Comment by mahyar-osn** [comment]
@williamFalcon Thanks worked perfectly!

**Comment by williamFalcon** [comment]
@mahyar-osn 👍
